/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Endpoints;
using MediatR;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Poseidon.Api.Exceptions;
using Poseidon.Application.CommandHandlers;
using Poseidon.Application.Commands;
using Poseidon.Application.Dto;
using Poseidon.Application.Helpers;
using Poseidon.Application.Queries;
using Poseidon.Enums;
using System.ComponentModel;

public static partial class Endpoints
{
////////////////////////////////////////////////////////
//// Address mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappAddress(this WebApplication app)
{
    app.MapGet("mediatr/address/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<AddressDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new AddressQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/address/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] AddressCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/address/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/address", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeleteAddressCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// Cart mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappCart(this WebApplication app)
{
    app.MapGet("mediatr/cart/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<CartDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new CartQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/cart/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] CartCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/cart/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/cart", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeleteCartCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// CartItem mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappCartItem(this WebApplication app)
{
    app.MapGet("mediatr/cartitem/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<CartItemDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new CartItemQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/cartitem/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] CartItemCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/cartitem/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/cartitem", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeleteCartItemCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// Category mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappCategory(this WebApplication app)
{
    app.MapGet("mediatr/category/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<CategoryDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new CategoryQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/category/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] CategoryCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/category/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/category", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeleteCategoryCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// Country mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappCountry(this WebApplication app)
{
    app.MapGet("mediatr/country/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<CountryDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new CountryQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/country/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] CountryCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/country/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/country", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeleteCountryCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// CreditCard mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappCreditCard(this WebApplication app)
{
    app.MapGet("mediatr/creditcard/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<CreditCardDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new CreditCardQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/creditcard/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] CreditCardCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/creditcard/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/creditcard", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeleteCreditCardCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// Delivery mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappDelivery(this WebApplication app)
{
    app.MapGet("mediatr/delivery/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<DeliveryDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new DeliveryQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/delivery/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] DeliveryCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/delivery/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/delivery", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeleteDeliveryCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// DiscountOffer mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappDiscountOffer(this WebApplication app)
{
    app.MapGet("mediatr/discountoffer/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<DiscountOfferDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new DiscountOfferQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/discountoffer/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] DiscountOfferCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/discountoffer/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/discountoffer", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeleteDiscountOfferCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// Order mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappOrder(this WebApplication app)
{
    app.MapGet("mediatr/order/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<OrderDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new OrderQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/order/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] OrderCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/order/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/order", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeleteOrderCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// OrderItem mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappOrderItem(this WebApplication app)
{
    app.MapGet("mediatr/orderitem/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<OrderItemDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new OrderItemQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/orderitem/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] OrderItemCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/orderitem/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/orderitem", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeleteOrderItemCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// Payment mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappPayment(this WebApplication app)
{
    app.MapGet("mediatr/payment/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<PaymentDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new PaymentQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/payment/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] PaymentCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/payment/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/payment", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeletePaymentCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// PaymentProvider mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappPaymentProvider(this WebApplication app)
{
    app.MapGet("mediatr/paymentprovider/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<PaymentProviderDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new PaymentProviderQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/paymentprovider/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] PaymentProviderCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/paymentprovider/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/paymentprovider", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeletePaymentProviderCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// Product mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappProduct(this WebApplication app)
{
    app.MapGet("mediatr/product/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<ProductDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new ProductQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/product/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] ProductCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/product/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/product", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeleteProductCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// ProductDiscountOffer mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappProductDiscountOffer(this WebApplication app)
{
    app.MapGet("mediatr/productdiscountoffer/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<ProductDiscountOfferDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new ProductDiscountOfferQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/productdiscountoffer/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] ProductDiscountOfferCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/productdiscountoffer/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/productdiscountoffer", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeleteProductDiscountOfferCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// Settings mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappSettings(this WebApplication app)
{
    app.MapGet("mediatr/settings/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<SettingsDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new SettingsQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/settings/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] SettingsCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/settings/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/settings", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeleteSettingsCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// TaxRate mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappTaxRate(this WebApplication app)
{
    app.MapGet("mediatr/taxrate/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<TaxRateDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new TaxRateQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/taxrate/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] TaxRateCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/taxrate/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/taxrate", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeleteTaxRateCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// User mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappUser(this WebApplication app)
{
    app.MapGet("mediatr/user/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<UserDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new UserQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/user/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] UserCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/user/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/user", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeleteUserCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// UserProductReview mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappUserProductReview(this WebApplication app)
{
    app.MapGet("mediatr/userproductreview/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<UserProductReviewDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new UserProductReviewQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/userproductreview/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] UserProductReviewCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/userproductreview/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/userproductreview", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeleteUserProductReviewCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// WishList mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappWishList(this WebApplication app)
{
    app.MapGet("mediatr/wishlist/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<WishListDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new WishListQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/wishlist/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] WishListCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/wishlist/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/wishlist", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeleteWishListCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// WishListItem mini api                          ///
//////////////////////////////////////////////////////// 
public static void MappWishListItem(this WebApplication app)
{
    app.MapGet("mediatr/wishlistitem/query",
    [ProducesResponseType(200, Type = (typeof(ResponseData<WishListItemDto>)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator             _mediator 
         , [FromQuery] [DefaultValue(1)]                         int?    page
         , [FromQuery] [DefaultValue(1000)]                      int?    pageSize
         , [FromQuery] [DefaultValue("Sys_UpdatedAt")]           string? orderBy 
         , [FromQuery] [DefaultValue("Sys_Deactivated != true")] string? filter
    ) =>
    { 
        return Results.Ok(await _mediator.Send(new WishListItemQuery(page, pageSize, filter, orderBy)));
    })
    .RequireAuthorization();
    
    app.MapPost("mediatr/wishlistitem/upsert", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(201, Type = (typeof(object)))]
    [ProducesResponseType(400, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(404, Type = (typeof(ErrorResponse)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ([FromServices] IMediator          _mediator 
         , [FromBody] WishListItemCommand   command) =>
    {
        var (id, status) = await _mediator.Send(command);

        return status is Status.Created 
               ? Results.Created($"mediatr/wishlistitem/upsert", id) 
               : Results.Ok(id);

    }).RequireAuthorization();

    app.MapDelete("mediatr/wishlistitem", 
    [ProducesResponseType(200, Type = (typeof(object)))]
    [ProducesResponseType(404, Type = (typeof(object)))]
    [ProducesResponseType(500, Type = (typeof(ErrorResponse)))]
    async ( [FromServices] IMediator          _mediator
          , [FromQuery] object id) =>
    {
       var (_id, status) = await _mediator.Send(new DeleteWishListItemCommand { Id = id });

       return status is Status.Deleted 
       ? Results.Ok(_id) 
       : Results.NotFound(_id);
    }).RequireAuthorization();

}
////////////////////////////////////////////////////////
//// Mapp all endpoints                              ///
//////////////////////////////////////////////////////// 
    public static void  MappEndpoints(this WebApplication app) 
    {
        app.MappAddress             ();
        app.MappCart                ();
        app.MappCartItem            ();
        app.MappCategory            ();
        app.MappCountry             ();
        app.MappCreditCard          ();
        app.MappDelivery            ();
        app.MappDiscountOffer       ();
        app.MappOrder               ();
        app.MappOrderItem           ();
        app.MappPayment             ();
        app.MappPaymentProvider     ();
        app.MappProduct             ();
        app.MappProductDiscountOffer();
        app.MappSettings            ();
        app.MappTaxRate             ();
        app.MappUser                ();
        app.MappUserProductReview   ();
        app.MappWishList            ();
        app.MappWishListItem        ();
        app.MappCustomEndpoints();
    }
} 
