/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Queries;
using MediatR;
using Poseidon.Application.Dto;
using Poseidon.Application.Helpers;


    public class AddressQuery :BaseQuery, IRequest<ResponseData<AddressDto>>
    { 
         public AddressQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }
    public class CartQuery :BaseQuery, IRequest<ResponseData<CartDto>>
    { 
         public CartQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }
    public class CartItemQuery :BaseQuery, IRequest<ResponseData<CartItemDto>>
    { 
         public CartItemQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }
    public class CategoryQuery :BaseQuery, IRequest<ResponseData<CategoryDto>>
    { 
         public CategoryQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }
    public class CountryQuery :BaseQuery, IRequest<ResponseData<CountryDto>>
    { 
         public CountryQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }
    public class CreditCardQuery :BaseQuery, IRequest<ResponseData<CreditCardDto>>
    { 
         public CreditCardQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }
    public class DeliveryQuery :BaseQuery, IRequest<ResponseData<DeliveryDto>>
    { 
         public DeliveryQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }
    public class DiscountOfferQuery :BaseQuery, IRequest<ResponseData<DiscountOfferDto>>
    { 
         public DiscountOfferQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }
    public class OrderQuery :BaseQuery, IRequest<ResponseData<OrderDto>>
    { 
         public OrderQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }
    public class OrderItemQuery :BaseQuery, IRequest<ResponseData<OrderItemDto>>
    { 
         public OrderItemQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }
    public class PaymentQuery :BaseQuery, IRequest<ResponseData<PaymentDto>>
    { 
         public PaymentQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }
    public class PaymentProviderQuery :BaseQuery, IRequest<ResponseData<PaymentProviderDto>>
    { 
         public PaymentProviderQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }
    public class ProductQuery :BaseQuery, IRequest<ResponseData<ProductDto>>
    { 
         public ProductQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }
    public class ProductDiscountOfferQuery :BaseQuery, IRequest<ResponseData<ProductDiscountOfferDto>>
    { 
         public ProductDiscountOfferQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }
    public class SettingsQuery :BaseQuery, IRequest<ResponseData<SettingsDto>>
    { 
         public SettingsQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }
    public class TaxRateQuery :BaseQuery, IRequest<ResponseData<TaxRateDto>>
    { 
         public TaxRateQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }
    public class UserQuery :BaseQuery, IRequest<ResponseData<UserDto>>
    { 
         public UserQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }
    public class UserProductReviewQuery :BaseQuery, IRequest<ResponseData<UserProductReviewDto>>
    { 
         public UserProductReviewQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }
    public class WishListQuery :BaseQuery, IRequest<ResponseData<WishListDto>>
    { 
         public WishListQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }
    public class WishListItemQuery :BaseQuery, IRequest<ResponseData<WishListItemDto>>
    { 
         public WishListItemQuery(int? page, int? size, string? filter, string? orderby) : base(page, size, filter, orderby){}
    }


