/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Dto;
 
    using System;
    using AutoMapper;
    using Poseidon.Domain;
    using System.Collections.Generic;


    public class AddressDto : IMapFrom<Address>
    { 
        public int             AddressId       { get; set; }
        public string          FirstName       { get; set; }
        public string          LastName        { get; set; }
        public string          Email           { get; set; }
        public string          Company         { get; set; }
        public string          County          { get; set; }
        public string          City            { get; set; }
        public string          Address1        { get; set; }
        public string          Address2        { get; set; }
        public string          ZipPostalCode   { get; set; }
        public string          PhoneNumber     { get; set; }
        public int             CountryId       { get; set; }
        public string          Sys_CreatedBy   { get; set; }
        public DateTimeOffset  Sys_CreatedAt   { get; set; }
        public string          Sys_UpdatedBy   { get; set; }
        public DateTimeOffset  Sys_UpdatedAt   { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< Address, AddressDto >()
             .ForMember(d => d.AddressId     , opt => opt.MapFrom(s => s.AddressId       ))
             .ForMember(d => d.FirstName     , opt => opt.MapFrom(s => s.FirstName       ))
             .ForMember(d => d.LastName      , opt => opt.MapFrom(s => s.LastName        ))
             .ForMember(d => d.Email         , opt => opt.MapFrom(s => s.Email           ))
             .ForMember(d => d.Company       , opt => opt.MapFrom(s => s.Company         ))
             .ForMember(d => d.County        , opt => opt.MapFrom(s => s.County          ))
             .ForMember(d => d.City          , opt => opt.MapFrom(s => s.City            ))
             .ForMember(d => d.Address1      , opt => opt.MapFrom(s => s.Address1        ))
             .ForMember(d => d.Address2      , opt => opt.MapFrom(s => s.Address2        ))
             .ForMember(d => d.ZipPostalCode , opt => opt.MapFrom(s => s.ZipPostalCode   ))
             .ForMember(d => d.PhoneNumber   , opt => opt.MapFrom(s => s.PhoneNumber     ))
             .ForMember(d => d.CountryId     , opt => opt.MapFrom(s => s.CountryId       ))
             .ForMember(d => d.Sys_CreatedBy , opt => opt.MapFrom(s => s.Sys_CreatedBy   ))
             .ForMember(d => d.Sys_CreatedAt , opt => opt.MapFrom(s => s.Sys_CreatedAt   ))
             .ForMember(d => d.Sys_UpdatedBy , opt => opt.MapFrom(s => s.Sys_UpdatedBy   ))
             .ForMember(d => d.Sys_UpdatedAt , opt => opt.MapFrom(s => s.Sys_UpdatedAt   ))
             ;
    }
    }



