/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Dto;
 
    using System;
    using AutoMapper;
    using Poseidon.Domain;
    using System.Collections.Generic;


    public class CartDto : IMapFrom<Cart>
    { 
        public int             CartId             { get; set; }
        public bool            IsActive           { get; set; }
        public bool?           LockedOnCheckout   { get; set; }
        public int             UserId             { get; set; }
        public decimal?        Total              { get; set; }
        public decimal?        TaxAmount          { get; set; }
        public decimal?        DiscountAmount     { get; set; }
        public string          Sys_CreatedBy      { get; set; }
        public DateTimeOffset  Sys_CreatedAt      { get; set; }
        public string          Sys_UpdatedBy      { get; set; }
        public DateTimeOffset  Sys_UpdatedAt      { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< Cart, CartDto >()
             .ForMember(d => d.CartId           , opt => opt.MapFrom(s => s.CartId             ))
             .ForMember(d => d.IsActive         , opt => opt.MapFrom(s => s.IsActive           ))
             .ForMember(d => d.LockedOnCheckout , opt => opt.MapFrom(s => s.LockedOnCheckout   ))
             .ForMember(d => d.UserId           , opt => opt.MapFrom(s => s.UserId             ))
             .ForMember(d => d.Total            , opt => opt.MapFrom(s => s.Total              ))
             .ForMember(d => d.TaxAmount        , opt => opt.MapFrom(s => s.TaxAmount          ))
             .ForMember(d => d.DiscountAmount   , opt => opt.MapFrom(s => s.DiscountAmount     ))
             .ForMember(d => d.Sys_CreatedBy    , opt => opt.MapFrom(s => s.Sys_CreatedBy      ))
             .ForMember(d => d.Sys_CreatedAt    , opt => opt.MapFrom(s => s.Sys_CreatedAt      ))
             .ForMember(d => d.Sys_UpdatedBy    , opt => opt.MapFrom(s => s.Sys_UpdatedBy      ))
             .ForMember(d => d.Sys_UpdatedAt    , opt => opt.MapFrom(s => s.Sys_UpdatedAt      ))
             ;
    }
    }



