/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Dto;
 
    using System;
    using AutoMapper;
    using Poseidon.Domain;
    using System.Collections.Generic;


    public class CartItemDto : IMapFrom<CartItem>
    { 
        public int             CartItemId       { get; set; }
        public decimal?        Quantity         { get; set; }
        public decimal?        Price            { get; set; }
        public decimal?        DiscountAmount   { get; set; }
        public decimal?        TaxAmount        { get; set; }
        public string          Title            { get; set; }
        public string          ImageUrl         { get; set; }
        public string          Unit             { get; set; }
        public int             CartId           { get; set; }
        public int             ProductId        { get; set; }
        public string          Sys_CreatedBy    { get; set; }
        public DateTimeOffset  Sys_CreatedAt    { get; set; }
        public string          Sys_UpdatedBy    { get; set; }
        public DateTimeOffset  Sys_UpdatedAt    { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< CartItem, CartItemDto >()
             .ForMember(d => d.CartItemId     , opt => opt.MapFrom(s => s.CartItemId       ))
             .ForMember(d => d.Quantity       , opt => opt.MapFrom(s => s.Quantity         ))
             .ForMember(d => d.Price          , opt => opt.MapFrom(s => s.Price            ))
             .ForMember(d => d.DiscountAmount , opt => opt.MapFrom(s => s.DiscountAmount   ))
             .ForMember(d => d.TaxAmount      , opt => opt.MapFrom(s => s.TaxAmount        ))
             .ForMember(d => d.Title          , opt => opt.MapFrom(s => s.Title            ))
             .ForMember(d => d.ImageUrl       , opt => opt.MapFrom(s => s.ImageUrl         ))
             .ForMember(d => d.Unit           , opt => opt.MapFrom(s => s.Unit             ))
             .ForMember(d => d.CartId         , opt => opt.MapFrom(s => s.CartId           ))
             .ForMember(d => d.ProductId      , opt => opt.MapFrom(s => s.ProductId        ))
             .ForMember(d => d.Sys_CreatedBy  , opt => opt.MapFrom(s => s.Sys_CreatedBy    ))
             .ForMember(d => d.Sys_CreatedAt  , opt => opt.MapFrom(s => s.Sys_CreatedAt    ))
             .ForMember(d => d.Sys_UpdatedBy  , opt => opt.MapFrom(s => s.Sys_UpdatedBy    ))
             .ForMember(d => d.Sys_UpdatedAt  , opt => opt.MapFrom(s => s.Sys_UpdatedAt    ))
             ;
    }
    }



