/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Dto;
 
    using System;
    using AutoMapper;
    using Poseidon.Domain;
    using System.Collections.Generic;


    public class CountryDto : IMapFrom<Country>
    { 
        public int             CountryId            { get; set; }
        public string          Name                 { get; set; }
        public string          TwoLetterIsoCode     { get; set; }
        public string          ThreeLetterIsoCode   { get; set; }
        public int             NumericIsoCode       { get; set; }
        public string          PhonePrefix          { get; set; }
        public string          Sys_CreatedBy        { get; set; }
        public DateTimeOffset  Sys_CreatedAt        { get; set; }
        public string          Sys_UpdatedBy        { get; set; }
        public DateTimeOffset  Sys_UpdatedAt        { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< Country, CountryDto >()
             .ForMember(d => d.CountryId          , opt => opt.MapFrom(s => s.CountryId            ))
             .ForMember(d => d.Name               , opt => opt.MapFrom(s => s.Name                 ))
             .ForMember(d => d.TwoLetterIsoCode   , opt => opt.MapFrom(s => s.TwoLetterIsoCode     ))
             .ForMember(d => d.ThreeLetterIsoCode , opt => opt.MapFrom(s => s.ThreeLetterIsoCode   ))
             .ForMember(d => d.NumericIsoCode     , opt => opt.MapFrom(s => s.NumericIsoCode       ))
             .ForMember(d => d.PhonePrefix        , opt => opt.MapFrom(s => s.PhonePrefix          ))
             .ForMember(d => d.Sys_CreatedBy      , opt => opt.MapFrom(s => s.Sys_CreatedBy        ))
             .ForMember(d => d.Sys_CreatedAt      , opt => opt.MapFrom(s => s.Sys_CreatedAt        ))
             .ForMember(d => d.Sys_UpdatedBy      , opt => opt.MapFrom(s => s.Sys_UpdatedBy        ))
             .ForMember(d => d.Sys_UpdatedAt      , opt => opt.MapFrom(s => s.Sys_UpdatedAt        ))
             ;
    }
    }



