/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Dto;
 
    using System;
    using AutoMapper;
    using Poseidon.Domain;
    using System.Collections.Generic;


    public class CreditCardDto : IMapFrom<CreditCard>
    { 
        public int             CreditCardId        { get; set; }
        public string          CreaditCartNumber   { get; set; }
        public string          CVC                 { get; set; }
        public DateTime        ExpirationDate      { get; set; }
        public string          ImageUrl            { get; set; }
        public int             UserId              { get; set; }
        public int             PaymentProviderId   { get; set; }
        public string          Sys_CreatedBy       { get; set; }
        public DateTimeOffset  Sys_CreatedAt       { get; set; }
        public string          Sys_UpdatedBy       { get; set; }
        public DateTimeOffset  Sys_UpdatedAt       { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< CreditCard, CreditCardDto >()
             .ForMember(d => d.CreditCardId      , opt => opt.MapFrom(s => s.CreditCardId        ))
             .ForMember(d => d.CreaditCartNumber , opt => opt.MapFrom(s => s.CreaditCartNumber   ))
             .ForMember(d => d.CVC               , opt => opt.MapFrom(s => s.CVC                 ))
             .ForMember(d => d.ExpirationDate    , opt => opt.MapFrom(s => s.ExpirationDate      ))
             .ForMember(d => d.ImageUrl          , opt => opt.MapFrom(s => s.ImageUrl            ))
             .ForMember(d => d.UserId            , opt => opt.MapFrom(s => s.UserId              ))
             .ForMember(d => d.PaymentProviderId , opt => opt.MapFrom(s => s.PaymentProviderId   ))
             .ForMember(d => d.Sys_CreatedBy     , opt => opt.MapFrom(s => s.Sys_CreatedBy       ))
             .ForMember(d => d.Sys_CreatedAt     , opt => opt.MapFrom(s => s.Sys_CreatedAt       ))
             .ForMember(d => d.Sys_UpdatedBy     , opt => opt.MapFrom(s => s.Sys_UpdatedBy       ))
             .ForMember(d => d.Sys_UpdatedAt     , opt => opt.MapFrom(s => s.Sys_UpdatedAt       ))
             ;
    }
    }



