/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Dto;
 
    using System;
    using AutoMapper;
    using Poseidon.Domain;
    using System.Collections.Generic;


    public class DeliveryDto : IMapFrom<Delivery>
    { 
        public int             DeliveryId      { get; set; }
        public string          Title           { get; set; }
        public string          Description     { get; set; }
        public bool            IsActive        { get; set; }
        public string          Sys_CreatedBy   { get; set; }
        public DateTimeOffset  Sys_CreatedAt   { get; set; }
        public string          Sys_UpdatedBy   { get; set; }
        public DateTimeOffset  Sys_UpdatedAt   { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< Delivery, DeliveryDto >()
             .ForMember(d => d.DeliveryId    , opt => opt.MapFrom(s => s.DeliveryId      ))
             .ForMember(d => d.Title         , opt => opt.MapFrom(s => s.Title           ))
             .ForMember(d => d.Description   , opt => opt.MapFrom(s => s.Description     ))
             .ForMember(d => d.IsActive      , opt => opt.MapFrom(s => s.IsActive        ))
             .ForMember(d => d.Sys_CreatedBy , opt => opt.MapFrom(s => s.Sys_CreatedBy   ))
             .ForMember(d => d.Sys_CreatedAt , opt => opt.MapFrom(s => s.Sys_CreatedAt   ))
             .ForMember(d => d.Sys_UpdatedBy , opt => opt.MapFrom(s => s.Sys_UpdatedBy   ))
             .ForMember(d => d.Sys_UpdatedAt , opt => opt.MapFrom(s => s.Sys_UpdatedAt   ))
             ;
    }
    }



