/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Dto;
 
    using System;
    using AutoMapper;
    using Poseidon.Domain;
    using System.Collections.Generic;


    public class DiscountOfferDto : IMapFrom<DiscountOffer>
    { 
        public int             DiscountOfferId   { get; set; }
        public string          Title             { get; set; }
        public string          Description       { get; set; }
        public string          ImageUrl          { get; set; }
        public DateTimeOffset  StartDate         { get; set; }
        public DateTimeOffset  EndDate           { get; set; }
        public decimal         Discount          { get; set; }
        public string          Sys_CreatedBy     { get; set; }
        public DateTimeOffset  Sys_CreatedAt     { get; set; }
        public string          Sys_UpdatedBy     { get; set; }
        public DateTimeOffset  Sys_UpdatedAt     { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< DiscountOffer, DiscountOfferDto >()
             .ForMember(d => d.DiscountOfferId , opt => opt.MapFrom(s => s.DiscountOfferId   ))
             .ForMember(d => d.Title           , opt => opt.MapFrom(s => s.Title             ))
             .ForMember(d => d.Description     , opt => opt.MapFrom(s => s.Description       ))
             .ForMember(d => d.ImageUrl        , opt => opt.MapFrom(s => s.ImageUrl          ))
             .ForMember(d => d.StartDate       , opt => opt.MapFrom(s => s.StartDate         ))
             .ForMember(d => d.EndDate         , opt => opt.MapFrom(s => s.EndDate           ))
             .ForMember(d => d.Discount        , opt => opt.MapFrom(s => s.Discount          ))
             .ForMember(d => d.Sys_CreatedBy   , opt => opt.MapFrom(s => s.Sys_CreatedBy     ))
             .ForMember(d => d.Sys_CreatedAt   , opt => opt.MapFrom(s => s.Sys_CreatedAt     ))
             .ForMember(d => d.Sys_UpdatedBy   , opt => opt.MapFrom(s => s.Sys_UpdatedBy     ))
             .ForMember(d => d.Sys_UpdatedAt   , opt => opt.MapFrom(s => s.Sys_UpdatedAt     ))
             ;
    }
    }



