/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Dto;
 
    using System;
    using AutoMapper;
    using Poseidon.Domain;
    using System.Collections.Generic;


    public partial class AddressDto : IMapFrom<Address>
    { 
        public object  AddressId       { get; set; }
        public object  FirstName       { get; set; }
        public object  LastName        { get; set; }
        public object  Email           { get; set; }
        public object  Company         { get; set; }
        public object  County          { get; set; }
        public object  City            { get; set; }
        public object  Address1        { get; set; }
        public object  Address2        { get; set; }
        public object  ZipPostalCode   { get; set; }
        public object  PhoneNumber     { get; set; }
        public object  CountryId       { get; set; }
        public object  Sys_CreatedBy   { get; set; }
        public object  Sys_CreatedAt   { get; set; }
        public object  Sys_UpdatedBy   { get; set; }
        public object  Sys_UpdatedAt   { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< Address, AddressDto >()
             .ForMember(d => d.AddressId     , opt => opt.MapFrom(s => s.AddressId       ))
             .ForMember(d => d.FirstName     , opt => opt.MapFrom(s => s.FirstName       ))
             .ForMember(d => d.LastName      , opt => opt.MapFrom(s => s.LastName        ))
             .ForMember(d => d.Email         , opt => opt.MapFrom(s => s.Email           ))
             .ForMember(d => d.Company       , opt => opt.MapFrom(s => s.Company         ))
             .ForMember(d => d.County        , opt => opt.MapFrom(s => s.County          ))
             .ForMember(d => d.City          , opt => opt.MapFrom(s => s.City            ))
             .ForMember(d => d.Address1      , opt => opt.MapFrom(s => s.Address1        ))
             .ForMember(d => d.Address2      , opt => opt.MapFrom(s => s.Address2        ))
             .ForMember(d => d.ZipPostalCode , opt => opt.MapFrom(s => s.ZipPostalCode   ))
             .ForMember(d => d.PhoneNumber   , opt => opt.MapFrom(s => s.PhoneNumber     ))
             .ForMember(d => d.CountryId     , opt => opt.MapFrom(s => s.CountryId       ))
             .ForMember(d => d.Sys_CreatedBy , opt => opt.MapFrom(s => s.Sys_CreatedBy   ))
             .ForMember(d => d.Sys_CreatedAt , opt => opt.MapFrom(s => s.Sys_CreatedAt   ))
             .ForMember(d => d.Sys_UpdatedBy , opt => opt.MapFrom(s => s.Sys_UpdatedBy   ))
             .ForMember(d => d.Sys_UpdatedAt , opt => opt.MapFrom(s => s.Sys_UpdatedAt   ))
             ;
    }
    }
    public partial class CartDto : IMapFrom<Cart>
    { 
        public object  CartId             { get; set; }
        public object  IsActive           { get; set; }
        public object  LockedOnCheckout   { get; set; }
        public object  UserId             { get; set; }
        public object  Total              { get; set; }
        public object  TaxAmount          { get; set; }
        public object  DiscountAmount     { get; set; }
        public object  Sys_CreatedBy      { get; set; }
        public object  Sys_CreatedAt      { get; set; }
        public object  Sys_UpdatedBy      { get; set; }
        public object  Sys_UpdatedAt      { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< Cart, CartDto >()
             .ForMember(d => d.CartId           , opt => opt.MapFrom(s => s.CartId             ))
             .ForMember(d => d.IsActive         , opt => opt.MapFrom(s => s.IsActive           ))
             .ForMember(d => d.LockedOnCheckout , opt => opt.MapFrom(s => s.LockedOnCheckout   ))
             .ForMember(d => d.UserId           , opt => opt.MapFrom(s => s.UserId             ))
             .ForMember(d => d.Total            , opt => opt.MapFrom(s => s.Total              ))
             .ForMember(d => d.TaxAmount        , opt => opt.MapFrom(s => s.TaxAmount          ))
             .ForMember(d => d.DiscountAmount   , opt => opt.MapFrom(s => s.DiscountAmount     ))
             .ForMember(d => d.Sys_CreatedBy    , opt => opt.MapFrom(s => s.Sys_CreatedBy      ))
             .ForMember(d => d.Sys_CreatedAt    , opt => opt.MapFrom(s => s.Sys_CreatedAt      ))
             .ForMember(d => d.Sys_UpdatedBy    , opt => opt.MapFrom(s => s.Sys_UpdatedBy      ))
             .ForMember(d => d.Sys_UpdatedAt    , opt => opt.MapFrom(s => s.Sys_UpdatedAt      ))
             ;
    }
    }
    public partial class CartItemDto : IMapFrom<CartItem>
    { 
        public object  CartItemId       { get; set; }
        public object  Quantity         { get; set; }
        public object  Price            { get; set; }
        public object  DiscountAmount   { get; set; }
        public object  TaxAmount        { get; set; }
        public object  Title            { get; set; }
        public object  ImageUrl         { get; set; }
        public object  Unit             { get; set; }
        public object  CartId           { get; set; }
        public object  ProductId        { get; set; }
        public object  Sys_CreatedBy    { get; set; }
        public object  Sys_CreatedAt    { get; set; }
        public object  Sys_UpdatedBy    { get; set; }
        public object  Sys_UpdatedAt    { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< CartItem, CartItemDto >()
             .ForMember(d => d.CartItemId     , opt => opt.MapFrom(s => s.CartItemId       ))
             .ForMember(d => d.Quantity       , opt => opt.MapFrom(s => s.Quantity         ))
             .ForMember(d => d.Price          , opt => opt.MapFrom(s => s.Price            ))
             .ForMember(d => d.DiscountAmount , opt => opt.MapFrom(s => s.DiscountAmount   ))
             .ForMember(d => d.TaxAmount      , opt => opt.MapFrom(s => s.TaxAmount        ))
             .ForMember(d => d.Title          , opt => opt.MapFrom(s => s.Title            ))
             .ForMember(d => d.ImageUrl       , opt => opt.MapFrom(s => s.ImageUrl         ))
             .ForMember(d => d.Unit           , opt => opt.MapFrom(s => s.Unit             ))
             .ForMember(d => d.CartId         , opt => opt.MapFrom(s => s.CartId           ))
             .ForMember(d => d.ProductId      , opt => opt.MapFrom(s => s.ProductId        ))
             .ForMember(d => d.Sys_CreatedBy  , opt => opt.MapFrom(s => s.Sys_CreatedBy    ))
             .ForMember(d => d.Sys_CreatedAt  , opt => opt.MapFrom(s => s.Sys_CreatedAt    ))
             .ForMember(d => d.Sys_UpdatedBy  , opt => opt.MapFrom(s => s.Sys_UpdatedBy    ))
             .ForMember(d => d.Sys_UpdatedAt  , opt => opt.MapFrom(s => s.Sys_UpdatedAt    ))
             ;
    }
    }
    public partial class CategoryDto : IMapFrom<Category>
    { 
        public object  CategoryId      { get; set; }
        public object  Name            { get; set; }
        public object  Sys_CreatedBy   { get; set; }
        public object  Sys_CreatedAt   { get; set; }
        public object  Sys_UpdatedBy   { get; set; }
        public object  Sys_UpdatedAt   { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< Category, CategoryDto >()
             .ForMember(d => d.CategoryId    , opt => opt.MapFrom(s => s.CategoryId      ))
             .ForMember(d => d.Name          , opt => opt.MapFrom(s => s.Name            ))
             .ForMember(d => d.Sys_CreatedBy , opt => opt.MapFrom(s => s.Sys_CreatedBy   ))
             .ForMember(d => d.Sys_CreatedAt , opt => opt.MapFrom(s => s.Sys_CreatedAt   ))
             .ForMember(d => d.Sys_UpdatedBy , opt => opt.MapFrom(s => s.Sys_UpdatedBy   ))
             .ForMember(d => d.Sys_UpdatedAt , opt => opt.MapFrom(s => s.Sys_UpdatedAt   ))
             ;
    }
    }
    public partial class CountryDto : IMapFrom<Country>
    { 
        public object  CountryId            { get; set; }
        public object  Name                 { get; set; }
        public object  TwoLetterIsoCode     { get; set; }
        public object  ThreeLetterIsoCode   { get; set; }
        public object  NumericIsoCode       { get; set; }
        public object  PhonePrefix          { get; set; }
        public object  Sys_CreatedBy        { get; set; }
        public object  Sys_CreatedAt        { get; set; }
        public object  Sys_UpdatedBy        { get; set; }
        public object  Sys_UpdatedAt        { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< Country, CountryDto >()
             .ForMember(d => d.CountryId          , opt => opt.MapFrom(s => s.CountryId            ))
             .ForMember(d => d.Name               , opt => opt.MapFrom(s => s.Name                 ))
             .ForMember(d => d.TwoLetterIsoCode   , opt => opt.MapFrom(s => s.TwoLetterIsoCode     ))
             .ForMember(d => d.ThreeLetterIsoCode , opt => opt.MapFrom(s => s.ThreeLetterIsoCode   ))
             .ForMember(d => d.NumericIsoCode     , opt => opt.MapFrom(s => s.NumericIsoCode       ))
             .ForMember(d => d.PhonePrefix        , opt => opt.MapFrom(s => s.PhonePrefix          ))
             .ForMember(d => d.Sys_CreatedBy      , opt => opt.MapFrom(s => s.Sys_CreatedBy        ))
             .ForMember(d => d.Sys_CreatedAt      , opt => opt.MapFrom(s => s.Sys_CreatedAt        ))
             .ForMember(d => d.Sys_UpdatedBy      , opt => opt.MapFrom(s => s.Sys_UpdatedBy        ))
             .ForMember(d => d.Sys_UpdatedAt      , opt => opt.MapFrom(s => s.Sys_UpdatedAt        ))
             ;
    }
    }
    public partial class CreditCardDto : IMapFrom<CreditCard>
    { 
        public object  CreditCardId        { get; set; }
        public object  CreaditCartNumber   { get; set; }
        public object  CVC                 { get; set; }
        public object  ExpirationDate      { get; set; }
        public object  ImageUrl            { get; set; }
        public object  UserId              { get; set; }
        public object  PaymentProviderId   { get; set; }
        public object  Sys_CreatedBy       { get; set; }
        public object  Sys_CreatedAt       { get; set; }
        public object  Sys_UpdatedBy       { get; set; }
        public object  Sys_UpdatedAt       { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< CreditCard, CreditCardDto >()
             .ForMember(d => d.CreditCardId      , opt => opt.MapFrom(s => s.CreditCardId        ))
             .ForMember(d => d.CreaditCartNumber , opt => opt.MapFrom(s => s.CreaditCartNumber   ))
             .ForMember(d => d.CVC               , opt => opt.MapFrom(s => s.CVC                 ))
             .ForMember(d => d.ExpirationDate    , opt => opt.MapFrom(s => s.ExpirationDate      ))
             .ForMember(d => d.ImageUrl          , opt => opt.MapFrom(s => s.ImageUrl            ))
             .ForMember(d => d.UserId            , opt => opt.MapFrom(s => s.UserId              ))
             .ForMember(d => d.PaymentProviderId , opt => opt.MapFrom(s => s.PaymentProviderId   ))
             .ForMember(d => d.Sys_CreatedBy     , opt => opt.MapFrom(s => s.Sys_CreatedBy       ))
             .ForMember(d => d.Sys_CreatedAt     , opt => opt.MapFrom(s => s.Sys_CreatedAt       ))
             .ForMember(d => d.Sys_UpdatedBy     , opt => opt.MapFrom(s => s.Sys_UpdatedBy       ))
             .ForMember(d => d.Sys_UpdatedAt     , opt => opt.MapFrom(s => s.Sys_UpdatedAt       ))
             ;
    }
    }
    public partial class DeliveryDto : IMapFrom<Delivery>
    { 
        public object  DeliveryId      { get; set; }
        public object  Title           { get; set; }
        public object  Description     { get; set; }
        public object  IsActive        { get; set; }
        public object  Sys_CreatedBy   { get; set; }
        public object  Sys_CreatedAt   { get; set; }
        public object  Sys_UpdatedBy   { get; set; }
        public object  Sys_UpdatedAt   { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< Delivery, DeliveryDto >()
             .ForMember(d => d.DeliveryId    , opt => opt.MapFrom(s => s.DeliveryId      ))
             .ForMember(d => d.Title         , opt => opt.MapFrom(s => s.Title           ))
             .ForMember(d => d.Description   , opt => opt.MapFrom(s => s.Description     ))
             .ForMember(d => d.IsActive      , opt => opt.MapFrom(s => s.IsActive        ))
             .ForMember(d => d.Sys_CreatedBy , opt => opt.MapFrom(s => s.Sys_CreatedBy   ))
             .ForMember(d => d.Sys_CreatedAt , opt => opt.MapFrom(s => s.Sys_CreatedAt   ))
             .ForMember(d => d.Sys_UpdatedBy , opt => opt.MapFrom(s => s.Sys_UpdatedBy   ))
             .ForMember(d => d.Sys_UpdatedAt , opt => opt.MapFrom(s => s.Sys_UpdatedAt   ))
             ;
    }
    }
    public partial class DiscountOfferDto : IMapFrom<DiscountOffer>
    { 
        public object  DiscountOfferId   { get; set; }
        public object  Title             { get; set; }
        public object  Description       { get; set; }
        public object  ImageUrl          { get; set; }
        public object  StartDate         { get; set; }
        public object  EndDate           { get; set; }
        public object  Discount          { get; set; }
        public object  Sys_CreatedBy     { get; set; }
        public object  Sys_CreatedAt     { get; set; }
        public object  Sys_UpdatedBy     { get; set; }
        public object  Sys_UpdatedAt     { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< DiscountOffer, DiscountOfferDto >()
             .ForMember(d => d.DiscountOfferId , opt => opt.MapFrom(s => s.DiscountOfferId   ))
             .ForMember(d => d.Title           , opt => opt.MapFrom(s => s.Title             ))
             .ForMember(d => d.Description     , opt => opt.MapFrom(s => s.Description       ))
             .ForMember(d => d.ImageUrl        , opt => opt.MapFrom(s => s.ImageUrl          ))
             .ForMember(d => d.StartDate       , opt => opt.MapFrom(s => s.StartDate         ))
             .ForMember(d => d.EndDate         , opt => opt.MapFrom(s => s.EndDate           ))
             .ForMember(d => d.Discount        , opt => opt.MapFrom(s => s.Discount          ))
             .ForMember(d => d.Sys_CreatedBy   , opt => opt.MapFrom(s => s.Sys_CreatedBy     ))
             .ForMember(d => d.Sys_CreatedAt   , opt => opt.MapFrom(s => s.Sys_CreatedAt     ))
             .ForMember(d => d.Sys_UpdatedBy   , opt => opt.MapFrom(s => s.Sys_UpdatedBy     ))
             .ForMember(d => d.Sys_UpdatedAt   , opt => opt.MapFrom(s => s.Sys_UpdatedAt     ))
             ;
    }
    }
    public partial class OrderDto : IMapFrom<Order>
    { 
        public object  OrderId                 { get; set; }
        public object  Description             { get; set; }
        public object  SubTotal                { get; set; }
        public object  ProductTaxAmount        { get; set; }
        public object  ProductDiscountAmount   { get; set; }
        public object  OrderDiscountAmount     { get; set; }
        public object  OrderTaxAmount          { get; set; }
        public object  OrderTotal              { get; set; }
        public object  OrderStatus             { get; set; }
        public object  PayedAndClosed          { get; set; }
        public object  ShippingMethod          { get; set; }
        public object  ShippingFeeAmount       { get; set; }
        public object  PaymentMethod           { get; set; }
        public object  PaymentFeeAmount        { get; set; }
        public object  ShippingAddressId       { get; set; }
        public object  BillingAddressId        { get; set; }
        public object  UserId                  { get; set; }
        public object  CartId                  { get; set; }
        public object  DeliveryId              { get; set; }
        public object  Sys_CreatedBy           { get; set; }
        public object  Sys_CreatedAt           { get; set; }
        public object  Sys_UpdatedBy           { get; set; }
        public object  Sys_UpdatedAt           { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< Order, OrderDto >()
             .ForMember(d => d.OrderId               , opt => opt.MapFrom(s => s.OrderId                 ))
             .ForMember(d => d.Description           , opt => opt.MapFrom(s => s.Description             ))
             .ForMember(d => d.SubTotal              , opt => opt.MapFrom(s => s.SubTotal                ))
             .ForMember(d => d.ProductTaxAmount      , opt => opt.MapFrom(s => s.ProductTaxAmount        ))
             .ForMember(d => d.ProductDiscountAmount , opt => opt.MapFrom(s => s.ProductDiscountAmount   ))
             .ForMember(d => d.OrderDiscountAmount   , opt => opt.MapFrom(s => s.OrderDiscountAmount     ))
             .ForMember(d => d.OrderTaxAmount        , opt => opt.MapFrom(s => s.OrderTaxAmount          ))
             .ForMember(d => d.OrderTotal            , opt => opt.MapFrom(s => s.OrderTotal              ))
             .ForMember(d => d.OrderStatus           , opt => opt.MapFrom(s => s.OrderStatus             ))
             .ForMember(d => d.PayedAndClosed        , opt => opt.MapFrom(s => s.PayedAndClosed          ))
             .ForMember(d => d.ShippingMethod        , opt => opt.MapFrom(s => s.ShippingMethod          ))
             .ForMember(d => d.ShippingFeeAmount     , opt => opt.MapFrom(s => s.ShippingFeeAmount       ))
             .ForMember(d => d.PaymentMethod         , opt => opt.MapFrom(s => s.PaymentMethod           ))
             .ForMember(d => d.PaymentFeeAmount      , opt => opt.MapFrom(s => s.PaymentFeeAmount        ))
             .ForMember(d => d.ShippingAddressId     , opt => opt.MapFrom(s => s.ShippingAddressId       ))
             .ForMember(d => d.BillingAddressId      , opt => opt.MapFrom(s => s.BillingAddressId        ))
             .ForMember(d => d.UserId                , opt => opt.MapFrom(s => s.UserId                  ))
             .ForMember(d => d.CartId                , opt => opt.MapFrom(s => s.CartId                  ))
             .ForMember(d => d.DeliveryId            , opt => opt.MapFrom(s => s.DeliveryId              ))
             .ForMember(d => d.Sys_CreatedBy         , opt => opt.MapFrom(s => s.Sys_CreatedBy           ))
             .ForMember(d => d.Sys_CreatedAt         , opt => opt.MapFrom(s => s.Sys_CreatedAt           ))
             .ForMember(d => d.Sys_UpdatedBy         , opt => opt.MapFrom(s => s.Sys_UpdatedBy           ))
             .ForMember(d => d.Sys_UpdatedAt         , opt => opt.MapFrom(s => s.Sys_UpdatedAt           ))
             ;
    }
    }
    public partial class OrderItemDto : IMapFrom<OrderItem>
    { 
        public object  OrderItemId      { get; set; }
        public object  ProductID        { get; set; }
        public object  OrderID          { get; set; }
        public object  ProductPrice     { get; set; }
        public object  Quantity         { get; set; }
        public object  DiscountAmount   { get; set; }
        public object  TaxAmount        { get; set; }
        public object  Sys_CreatedBy    { get; set; }
        public object  Sys_CreatedAt    { get; set; }
        public object  Sys_UpdatedBy    { get; set; }
        public object  Sys_UpdatedAt    { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< OrderItem, OrderItemDto >()
             .ForMember(d => d.OrderItemId    , opt => opt.MapFrom(s => s.OrderItemId      ))
             .ForMember(d => d.ProductID      , opt => opt.MapFrom(s => s.ProductID        ))
             .ForMember(d => d.OrderID        , opt => opt.MapFrom(s => s.OrderID          ))
             .ForMember(d => d.ProductPrice   , opt => opt.MapFrom(s => s.ProductPrice     ))
             .ForMember(d => d.Quantity       , opt => opt.MapFrom(s => s.Quantity         ))
             .ForMember(d => d.DiscountAmount , opt => opt.MapFrom(s => s.DiscountAmount   ))
             .ForMember(d => d.TaxAmount      , opt => opt.MapFrom(s => s.TaxAmount        ))
             .ForMember(d => d.Sys_CreatedBy  , opt => opt.MapFrom(s => s.Sys_CreatedBy    ))
             .ForMember(d => d.Sys_CreatedAt  , opt => opt.MapFrom(s => s.Sys_CreatedAt    ))
             .ForMember(d => d.Sys_UpdatedBy  , opt => opt.MapFrom(s => s.Sys_UpdatedBy    ))
             .ForMember(d => d.Sys_UpdatedAt  , opt => opt.MapFrom(s => s.Sys_UpdatedAt    ))
             ;
    }
    }
    public partial class PaymentDto : IMapFrom<Payment>
    { 
        public object  PaymentId           { get; set; }
        public object  Amount              { get; set; }
        public object  PaymentFee          { get; set; }
        public object  FailureMessage      { get; set; }
        public object  OrderId             { get; set; }
        public object  PaymentProviderId   { get; set; }
        public object  Sys_CreatedBy       { get; set; }
        public object  Sys_CreatedAt       { get; set; }
        public object  Sys_UpdatedBy       { get; set; }
        public object  Sys_UpdatedAt       { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< Payment, PaymentDto >()
             .ForMember(d => d.PaymentId         , opt => opt.MapFrom(s => s.PaymentId           ))
             .ForMember(d => d.Amount            , opt => opt.MapFrom(s => s.Amount              ))
             .ForMember(d => d.PaymentFee        , opt => opt.MapFrom(s => s.PaymentFee          ))
             .ForMember(d => d.FailureMessage    , opt => opt.MapFrom(s => s.FailureMessage      ))
             .ForMember(d => d.OrderId           , opt => opt.MapFrom(s => s.OrderId             ))
             .ForMember(d => d.PaymentProviderId , opt => opt.MapFrom(s => s.PaymentProviderId   ))
             .ForMember(d => d.Sys_CreatedBy     , opt => opt.MapFrom(s => s.Sys_CreatedBy       ))
             .ForMember(d => d.Sys_CreatedAt     , opt => opt.MapFrom(s => s.Sys_CreatedAt       ))
             .ForMember(d => d.Sys_UpdatedBy     , opt => opt.MapFrom(s => s.Sys_UpdatedBy       ))
             .ForMember(d => d.Sys_UpdatedAt     , opt => opt.MapFrom(s => s.Sys_UpdatedAt       ))
             ;
    }
    }
    public partial class PaymentProviderDto : IMapFrom<PaymentProvider>
    { 
        public object  PaymentProviderId    { get; set; }
        public object  Name                 { get; set; }
        public object  IsEnabled            { get; set; }
        public object  AdditionalSettings   { get; set; }
        public object  Sys_CreatedBy        { get; set; }
        public object  Sys_CreatedAt        { get; set; }
        public object  Sys_UpdatedBy        { get; set; }
        public object  Sys_UpdatedAt        { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< PaymentProvider, PaymentProviderDto >()
             .ForMember(d => d.PaymentProviderId  , opt => opt.MapFrom(s => s.PaymentProviderId    ))
             .ForMember(d => d.Name               , opt => opt.MapFrom(s => s.Name                 ))
             .ForMember(d => d.IsEnabled          , opt => opt.MapFrom(s => s.IsEnabled            ))
             .ForMember(d => d.AdditionalSettings , opt => opt.MapFrom(s => s.AdditionalSettings   ))
             .ForMember(d => d.Sys_CreatedBy      , opt => opt.MapFrom(s => s.Sys_CreatedBy        ))
             .ForMember(d => d.Sys_CreatedAt      , opt => opt.MapFrom(s => s.Sys_CreatedAt        ))
             .ForMember(d => d.Sys_UpdatedBy      , opt => opt.MapFrom(s => s.Sys_UpdatedBy        ))
             .ForMember(d => d.Sys_UpdatedAt      , opt => opt.MapFrom(s => s.Sys_UpdatedAt        ))
             ;
    }
    }
    public partial class ProductDto : IMapFrom<Product>
    { 
        public object  ProductId       { get; set; }
        public object  Name            { get; set; }
        public object  Number          { get; set; }
        public object  ImageUrl        { get; set; }
        public object  Unit            { get; set; }
        public object  Price           { get; set; }
        public object  Description     { get; set; }
        public object  Gtin            { get; set; }
        public object  Supplier        { get; set; }
        public object  TaxRateId       { get; set; }
        public object  CategoryId      { get; set; }
        public object  Sys_CreatedBy   { get; set; }
        public object  Sys_CreatedAt   { get; set; }
        public object  Sys_UpdatedBy   { get; set; }
        public object  Sys_UpdatedAt   { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< Product, ProductDto >()
             .ForMember(d => d.ProductId     , opt => opt.MapFrom(s => s.ProductId       ))
             .ForMember(d => d.Name          , opt => opt.MapFrom(s => s.Name            ))
             .ForMember(d => d.Number        , opt => opt.MapFrom(s => s.Number          ))
             .ForMember(d => d.ImageUrl      , opt => opt.MapFrom(s => s.ImageUrl        ))
             .ForMember(d => d.Unit          , opt => opt.MapFrom(s => s.Unit            ))
             .ForMember(d => d.Price         , opt => opt.MapFrom(s => s.Price           ))
             .ForMember(d => d.Description   , opt => opt.MapFrom(s => s.Description     ))
             .ForMember(d => d.Gtin          , opt => opt.MapFrom(s => s.Gtin            ))
             .ForMember(d => d.Supplier      , opt => opt.MapFrom(s => s.Supplier        ))
             .ForMember(d => d.TaxRateId     , opt => opt.MapFrom(s => s.TaxRateId       ))
             .ForMember(d => d.CategoryId    , opt => opt.MapFrom(s => s.CategoryId      ))
             .ForMember(d => d.Sys_CreatedBy , opt => opt.MapFrom(s => s.Sys_CreatedBy   ))
             .ForMember(d => d.Sys_CreatedAt , opt => opt.MapFrom(s => s.Sys_CreatedAt   ))
             .ForMember(d => d.Sys_UpdatedBy , opt => opt.MapFrom(s => s.Sys_UpdatedBy   ))
             .ForMember(d => d.Sys_UpdatedAt , opt => opt.MapFrom(s => s.Sys_UpdatedAt   ))
             ;
    }
    }
    public partial class ProductDiscountOfferDto : IMapFrom<ProductDiscountOffer>
    { 
        public object  ProductDiscountOfferId   { get; set; }
        public object  ProductID                { get; set; }
        public object  DiscountOfferID          { get; set; }
        public object  Sys_CreatedBy            { get; set; }
        public object  Sys_CreatedAt            { get; set; }
        public object  Sys_UpdatedBy            { get; set; }
        public object  Sys_UpdatedAt            { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< ProductDiscountOffer, ProductDiscountOfferDto >()
             .ForMember(d => d.ProductDiscountOfferId , opt => opt.MapFrom(s => s.ProductDiscountOfferId   ))
             .ForMember(d => d.ProductID              , opt => opt.MapFrom(s => s.ProductID                ))
             .ForMember(d => d.DiscountOfferID        , opt => opt.MapFrom(s => s.DiscountOfferID          ))
             .ForMember(d => d.Sys_CreatedBy          , opt => opt.MapFrom(s => s.Sys_CreatedBy            ))
             .ForMember(d => d.Sys_CreatedAt          , opt => opt.MapFrom(s => s.Sys_CreatedAt            ))
             .ForMember(d => d.Sys_UpdatedBy          , opt => opt.MapFrom(s => s.Sys_UpdatedBy            ))
             .ForMember(d => d.Sys_UpdatedAt          , opt => opt.MapFrom(s => s.Sys_UpdatedAt            ))
             ;
    }
    }
    public partial class SettingsDto : IMapFrom<Settings>
    { 
        public object  SettingsId            { get; set; }
        public object  Description           { get; set; }
        public object  OrderDiscountAmount   { get; set; }
        public object  OrderTaxAmount        { get; set; }
        public object  PaymentFeeAmount      { get; set; }
        public object  ShippingFeeAmount     { get; set; }
        public object  ShippingMethod        { get; set; }
        public object  PaymentMethod         { get; set; }
        public object  Supplier              { get; set; }
        public object  Sys_CreatedBy         { get; set; }
        public object  Sys_CreatedAt         { get; set; }
        public object  Sys_UpdatedBy         { get; set; }
        public object  Sys_UpdatedAt         { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< Settings, SettingsDto >()
             .ForMember(d => d.SettingsId          , opt => opt.MapFrom(s => s.SettingsId            ))
             .ForMember(d => d.Description         , opt => opt.MapFrom(s => s.Description           ))
             .ForMember(d => d.OrderDiscountAmount , opt => opt.MapFrom(s => s.OrderDiscountAmount   ))
             .ForMember(d => d.OrderTaxAmount      , opt => opt.MapFrom(s => s.OrderTaxAmount        ))
             .ForMember(d => d.PaymentFeeAmount    , opt => opt.MapFrom(s => s.PaymentFeeAmount      ))
             .ForMember(d => d.ShippingFeeAmount   , opt => opt.MapFrom(s => s.ShippingFeeAmount     ))
             .ForMember(d => d.ShippingMethod      , opt => opt.MapFrom(s => s.ShippingMethod        ))
             .ForMember(d => d.PaymentMethod       , opt => opt.MapFrom(s => s.PaymentMethod         ))
             .ForMember(d => d.Supplier            , opt => opt.MapFrom(s => s.Supplier              ))
             .ForMember(d => d.Sys_CreatedBy       , opt => opt.MapFrom(s => s.Sys_CreatedBy         ))
             .ForMember(d => d.Sys_CreatedAt       , opt => opt.MapFrom(s => s.Sys_CreatedAt         ))
             .ForMember(d => d.Sys_UpdatedBy       , opt => opt.MapFrom(s => s.Sys_UpdatedBy         ))
             .ForMember(d => d.Sys_UpdatedAt       , opt => opt.MapFrom(s => s.Sys_UpdatedAt         ))
             ;
    }
    }
    public partial class TaxRateDto : IMapFrom<TaxRate>
    { 
        public object  TaxRateId       { get; set; }
        public object  Name            { get; set; }
        public object  Rate            { get; set; }
        public object  Sys_CreatedBy   { get; set; }
        public object  Sys_CreatedAt   { get; set; }
        public object  Sys_UpdatedBy   { get; set; }
        public object  Sys_UpdatedAt   { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< TaxRate, TaxRateDto >()
             .ForMember(d => d.TaxRateId     , opt => opt.MapFrom(s => s.TaxRateId       ))
             .ForMember(d => d.Name          , opt => opt.MapFrom(s => s.Name            ))
             .ForMember(d => d.Rate          , opt => opt.MapFrom(s => s.Rate            ))
             .ForMember(d => d.Sys_CreatedBy , opt => opt.MapFrom(s => s.Sys_CreatedBy   ))
             .ForMember(d => d.Sys_CreatedAt , opt => opt.MapFrom(s => s.Sys_CreatedAt   ))
             .ForMember(d => d.Sys_UpdatedBy , opt => opt.MapFrom(s => s.Sys_UpdatedBy   ))
             .ForMember(d => d.Sys_UpdatedAt , opt => opt.MapFrom(s => s.Sys_UpdatedAt   ))
             ;
    }
    }
    public partial class UserDto : IMapFrom<User>
    { 
        public object  UserId          { get; set; }
        public object  ExternalRef     { get; set; }
        public object  Username        { get; set; }
        public object  FirstName       { get; set; }
        public object  PhoneNumber     { get; set; }
        public object  LastName        { get; set; }
        public object  Email           { get; set; }
        public object  ImageUrl        { get; set; }
        public object  AddressId       { get; set; }
        public object  Sys_CreatedBy   { get; set; }
        public object  Sys_CreatedAt   { get; set; }
        public object  Sys_UpdatedBy   { get; set; }
        public object  Sys_UpdatedAt   { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< User, UserDto >()
             .ForMember(d => d.UserId        , opt => opt.MapFrom(s => s.UserId          ))
             .ForMember(d => d.ExternalRef   , opt => opt.MapFrom(s => s.ExternalRef     ))
             .ForMember(d => d.Username      , opt => opt.MapFrom(s => s.Username        ))
             .ForMember(d => d.FirstName     , opt => opt.MapFrom(s => s.FirstName       ))
             .ForMember(d => d.PhoneNumber   , opt => opt.MapFrom(s => s.PhoneNumber     ))
             .ForMember(d => d.LastName      , opt => opt.MapFrom(s => s.LastName        ))
             .ForMember(d => d.Email         , opt => opt.MapFrom(s => s.Email           ))
             .ForMember(d => d.ImageUrl      , opt => opt.MapFrom(s => s.ImageUrl        ))
             .ForMember(d => d.AddressId     , opt => opt.MapFrom(s => s.AddressId       ))
             .ForMember(d => d.Sys_CreatedBy , opt => opt.MapFrom(s => s.Sys_CreatedBy   ))
             .ForMember(d => d.Sys_CreatedAt , opt => opt.MapFrom(s => s.Sys_CreatedAt   ))
             .ForMember(d => d.Sys_UpdatedBy , opt => opt.MapFrom(s => s.Sys_UpdatedBy   ))
             .ForMember(d => d.Sys_UpdatedAt , opt => opt.MapFrom(s => s.Sys_UpdatedAt   ))
             ;
    }
    }
    public partial class UserProductReviewDto : IMapFrom<UserProductReview>
    { 
        public object  UserProductReviewId   { get; set; }
        public object  UserID                { get; set; }
        public object  ProductID             { get; set; }
        public object  Title                 { get; set; }
        public object  Comment               { get; set; }
        public object  Rating                { get; set; }
        public object  Sys_CreatedBy         { get; set; }
        public object  Sys_CreatedAt         { get; set; }
        public object  Sys_UpdatedBy         { get; set; }
        public object  Sys_UpdatedAt         { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< UserProductReview, UserProductReviewDto >()
             .ForMember(d => d.UserProductReviewId , opt => opt.MapFrom(s => s.UserProductReviewId   ))
             .ForMember(d => d.UserID              , opt => opt.MapFrom(s => s.UserID                ))
             .ForMember(d => d.ProductID           , opt => opt.MapFrom(s => s.ProductID             ))
             .ForMember(d => d.Title               , opt => opt.MapFrom(s => s.Title                 ))
             .ForMember(d => d.Comment             , opt => opt.MapFrom(s => s.Comment               ))
             .ForMember(d => d.Rating              , opt => opt.MapFrom(s => s.Rating                ))
             .ForMember(d => d.Sys_CreatedBy       , opt => opt.MapFrom(s => s.Sys_CreatedBy         ))
             .ForMember(d => d.Sys_CreatedAt       , opt => opt.MapFrom(s => s.Sys_CreatedAt         ))
             .ForMember(d => d.Sys_UpdatedBy       , opt => opt.MapFrom(s => s.Sys_UpdatedBy         ))
             .ForMember(d => d.Sys_UpdatedAt       , opt => opt.MapFrom(s => s.Sys_UpdatedAt         ))
             ;
    }
    }
    public partial class WishListDto : IMapFrom<WishList>
    { 
        public object  WishListId      { get; set; }
        public object  Title           { get; set; }
        public object  Description     { get; set; }
        public object  UserId          { get; set; }
        public object  Sys_CreatedBy   { get; set; }
        public object  Sys_CreatedAt   { get; set; }
        public object  Sys_UpdatedBy   { get; set; }
        public object  Sys_UpdatedAt   { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< WishList, WishListDto >()
             .ForMember(d => d.WishListId    , opt => opt.MapFrom(s => s.WishListId      ))
             .ForMember(d => d.Title         , opt => opt.MapFrom(s => s.Title           ))
             .ForMember(d => d.Description   , opt => opt.MapFrom(s => s.Description     ))
             .ForMember(d => d.UserId        , opt => opt.MapFrom(s => s.UserId          ))
             .ForMember(d => d.Sys_CreatedBy , opt => opt.MapFrom(s => s.Sys_CreatedBy   ))
             .ForMember(d => d.Sys_CreatedAt , opt => opt.MapFrom(s => s.Sys_CreatedAt   ))
             .ForMember(d => d.Sys_UpdatedBy , opt => opt.MapFrom(s => s.Sys_UpdatedBy   ))
             .ForMember(d => d.Sys_UpdatedAt , opt => opt.MapFrom(s => s.Sys_UpdatedAt   ))
             ;
    }
    }
    public partial class WishListItemDto : IMapFrom<WishListItem>
    { 
        public object  WishListItemId   { get; set; }
        public object  Note             { get; set; }
        public object  Quantity         { get; set; }
        public object  WishListId       { get; set; }
        public object  ProductId        { get; set; }
        public object  Sys_CreatedBy    { get; set; }
        public object  Sys_CreatedAt    { get; set; }
        public object  Sys_UpdatedBy    { get; set; }
        public object  Sys_UpdatedAt    { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< WishListItem, WishListItemDto >()
             .ForMember(d => d.WishListItemId , opt => opt.MapFrom(s => s.WishListItemId   ))
             .ForMember(d => d.Note           , opt => opt.MapFrom(s => s.Note             ))
             .ForMember(d => d.Quantity       , opt => opt.MapFrom(s => s.Quantity         ))
             .ForMember(d => d.WishListId     , opt => opt.MapFrom(s => s.WishListId       ))
             .ForMember(d => d.ProductId      , opt => opt.MapFrom(s => s.ProductId        ))
             .ForMember(d => d.Sys_CreatedBy  , opt => opt.MapFrom(s => s.Sys_CreatedBy    ))
             .ForMember(d => d.Sys_CreatedAt  , opt => opt.MapFrom(s => s.Sys_CreatedAt    ))
             .ForMember(d => d.Sys_UpdatedBy  , opt => opt.MapFrom(s => s.Sys_UpdatedBy    ))
             .ForMember(d => d.Sys_UpdatedAt  , opt => opt.MapFrom(s => s.Sys_UpdatedAt    ))
             ;
    }
    }



