/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Dto;
 
    using System;
    using AutoMapper;
    using Poseidon.Domain;
    using System.Collections.Generic;


    public class OrderItemDto : IMapFrom<OrderItem>
    { 
        public int             OrderItemId      { get; set; }
        public int             ProductId        { get; set; }
        public int             OrderId          { get; set; }
        public decimal         ProductPrice     { get; set; }
        public decimal         Quantity         { get; set; }
        public decimal         DiscountAmount   { get; set; }
        public decimal         TaxAmount        { get; set; }
        public string          Sys_CreatedBy    { get; set; }
        public DateTimeOffset  Sys_CreatedAt    { get; set; }
        public string          Sys_UpdatedBy    { get; set; }
        public DateTimeOffset  Sys_UpdatedAt    { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< OrderItem, OrderItemDto >()
             .ForMember(d => d.OrderItemId    , opt => opt.MapFrom(s => s.OrderItemId      ))
             .ForMember(d => d.ProductId      , opt => opt.MapFrom(s => s.ProductId        ))
             .ForMember(d => d.OrderId        , opt => opt.MapFrom(s => s.OrderId          ))
             .ForMember(d => d.ProductPrice   , opt => opt.MapFrom(s => s.ProductPrice     ))
             .ForMember(d => d.Quantity       , opt => opt.MapFrom(s => s.Quantity         ))
             .ForMember(d => d.DiscountAmount , opt => opt.MapFrom(s => s.DiscountAmount   ))
             .ForMember(d => d.TaxAmount      , opt => opt.MapFrom(s => s.TaxAmount        ))
             .ForMember(d => d.Sys_CreatedBy  , opt => opt.MapFrom(s => s.Sys_CreatedBy    ))
             .ForMember(d => d.Sys_CreatedAt  , opt => opt.MapFrom(s => s.Sys_CreatedAt    ))
             .ForMember(d => d.Sys_UpdatedBy  , opt => opt.MapFrom(s => s.Sys_UpdatedBy    ))
             .ForMember(d => d.Sys_UpdatedAt  , opt => opt.MapFrom(s => s.Sys_UpdatedAt    ))
             ;
    }
    }



