/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Dto;
 
    using System;
    using AutoMapper;
    using Poseidon.Domain;
    using System.Collections.Generic;


    public class OrderDto : IMapFrom<Order>
    { 
        public int             OrderId                 { get; set; }
        public string          Description             { get; set; }
        public decimal         SubTotal                { get; set; }
        public decimal         ProductTaxAmount        { get; set; }
        public decimal         ProductDiscountAmount   { get; set; }
        public decimal         OrderDiscountAmount     { get; set; }
        public decimal         OrderTaxAmount          { get; set; }
        public decimal         OrderTotal              { get; set; }
        public string          OrderStatus             { get; set; }
        public bool            PayedAndClosed          { get; set; }
        public string          ShippingMethod          { get; set; }
        public decimal         ShippingFeeAmount       { get; set; }
        public string          PaymentMethod           { get; set; }
        public decimal         PaymentFeeAmount        { get; set; }
        public int?            ShippingAddressId       { get; set; }
        public int?            BillingAddressId        { get; set; }
        public int             UserId                  { get; set; }
        public int?            CartId                  { get; set; }
        public int?            DeliveryId              { get; set; }
        public string          Sys_CreatedBy           { get; set; }
        public DateTimeOffset  Sys_CreatedAt           { get; set; }
        public string          Sys_UpdatedBy           { get; set; }
        public DateTimeOffset  Sys_UpdatedAt           { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< Order, OrderDto >()
             .ForMember(d => d.OrderId               , opt => opt.MapFrom(s => s.OrderId                 ))
             .ForMember(d => d.Description           , opt => opt.MapFrom(s => s.Description             ))
             .ForMember(d => d.SubTotal              , opt => opt.MapFrom(s => s.SubTotal                ))
             .ForMember(d => d.ProductTaxAmount      , opt => opt.MapFrom(s => s.ProductTaxAmount        ))
             .ForMember(d => d.ProductDiscountAmount , opt => opt.MapFrom(s => s.ProductDiscountAmount   ))
             .ForMember(d => d.OrderDiscountAmount   , opt => opt.MapFrom(s => s.OrderDiscountAmount     ))
             .ForMember(d => d.OrderTaxAmount        , opt => opt.MapFrom(s => s.OrderTaxAmount          ))
             .ForMember(d => d.OrderTotal            , opt => opt.MapFrom(s => s.OrderTotal              ))
             .ForMember(d => d.OrderStatus           , opt => opt.MapFrom(s => s.OrderStatus             ))
             .ForMember(d => d.PayedAndClosed        , opt => opt.MapFrom(s => s.PayedAndClosed          ))
             .ForMember(d => d.ShippingMethod        , opt => opt.MapFrom(s => s.ShippingMethod          ))
             .ForMember(d => d.ShippingFeeAmount     , opt => opt.MapFrom(s => s.ShippingFeeAmount       ))
             .ForMember(d => d.PaymentMethod         , opt => opt.MapFrom(s => s.PaymentMethod           ))
             .ForMember(d => d.PaymentFeeAmount      , opt => opt.MapFrom(s => s.PaymentFeeAmount        ))
             .ForMember(d => d.ShippingAddressId     , opt => opt.MapFrom(s => s.ShippingAddressId       ))
             .ForMember(d => d.BillingAddressId      , opt => opt.MapFrom(s => s.BillingAddressId        ))
             .ForMember(d => d.UserId                , opt => opt.MapFrom(s => s.UserId                  ))
             .ForMember(d => d.CartId                , opt => opt.MapFrom(s => s.CartId                  ))
             .ForMember(d => d.DeliveryId            , opt => opt.MapFrom(s => s.DeliveryId              ))
             .ForMember(d => d.Sys_CreatedBy         , opt => opt.MapFrom(s => s.Sys_CreatedBy           ))
             .ForMember(d => d.Sys_CreatedAt         , opt => opt.MapFrom(s => s.Sys_CreatedAt           ))
             .ForMember(d => d.Sys_UpdatedBy         , opt => opt.MapFrom(s => s.Sys_UpdatedBy           ))
             .ForMember(d => d.Sys_UpdatedAt         , opt => opt.MapFrom(s => s.Sys_UpdatedAt           ))
             ;
    }
    }



