/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Dto;
 
    using System;
    using AutoMapper;
    using Poseidon.Domain;
    using System.Collections.Generic;


    public class PaymentDto : IMapFrom<Payment>
    { 
        public int             PaymentId           { get; set; }
        public decimal         Amount              { get; set; }
        public decimal         PaymentFee          { get; set; }
        public string          FailureMessage      { get; set; }
        public int             OrderId             { get; set; }
        public int             PaymentProviderId   { get; set; }
        public string          Sys_CreatedBy       { get; set; }
        public DateTimeOffset  Sys_CreatedAt       { get; set; }
        public string          Sys_UpdatedBy       { get; set; }
        public DateTimeOffset  Sys_UpdatedAt       { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< Payment, PaymentDto >()
             .ForMember(d => d.PaymentId         , opt => opt.MapFrom(s => s.PaymentId           ))
             .ForMember(d => d.Amount            , opt => opt.MapFrom(s => s.Amount              ))
             .ForMember(d => d.PaymentFee        , opt => opt.MapFrom(s => s.PaymentFee          ))
             .ForMember(d => d.FailureMessage    , opt => opt.MapFrom(s => s.FailureMessage      ))
             .ForMember(d => d.OrderId           , opt => opt.MapFrom(s => s.OrderId             ))
             .ForMember(d => d.PaymentProviderId , opt => opt.MapFrom(s => s.PaymentProviderId   ))
             .ForMember(d => d.Sys_CreatedBy     , opt => opt.MapFrom(s => s.Sys_CreatedBy       ))
             .ForMember(d => d.Sys_CreatedAt     , opt => opt.MapFrom(s => s.Sys_CreatedAt       ))
             .ForMember(d => d.Sys_UpdatedBy     , opt => opt.MapFrom(s => s.Sys_UpdatedBy       ))
             .ForMember(d => d.Sys_UpdatedAt     , opt => opt.MapFrom(s => s.Sys_UpdatedAt       ))
             ;
    }
    }



