/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Dto;
 
    using System;
    using AutoMapper;
    using Poseidon.Domain;
    using System.Collections.Generic;


    public class PaymentProviderDto : IMapFrom<PaymentProvider>
    { 
        public int             PaymentProviderId    { get; set; }
        public string          Name                 { get; set; }
        public bool            IsEnabled            { get; set; }
        public string          AdditionalSettings   { get; set; }
        public string          Sys_CreatedBy        { get; set; }
        public DateTimeOffset  Sys_CreatedAt        { get; set; }
        public string          Sys_UpdatedBy        { get; set; }
        public DateTimeOffset  Sys_UpdatedAt        { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< PaymentProvider, PaymentProviderDto >()
             .ForMember(d => d.PaymentProviderId  , opt => opt.MapFrom(s => s.PaymentProviderId    ))
             .ForMember(d => d.Name               , opt => opt.MapFrom(s => s.Name                 ))
             .ForMember(d => d.IsEnabled          , opt => opt.MapFrom(s => s.IsEnabled            ))
             .ForMember(d => d.AdditionalSettings , opt => opt.MapFrom(s => s.AdditionalSettings   ))
             .ForMember(d => d.Sys_CreatedBy      , opt => opt.MapFrom(s => s.Sys_CreatedBy        ))
             .ForMember(d => d.Sys_CreatedAt      , opt => opt.MapFrom(s => s.Sys_CreatedAt        ))
             .ForMember(d => d.Sys_UpdatedBy      , opt => opt.MapFrom(s => s.Sys_UpdatedBy        ))
             .ForMember(d => d.Sys_UpdatedAt      , opt => opt.MapFrom(s => s.Sys_UpdatedAt        ))
             ;
    }
    }



