/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Dto;
 
    using System;
    using AutoMapper;
    using Poseidon.Domain;
    using System.Collections.Generic;


    public class ProductDiscountOfferDto : IMapFrom<ProductDiscountOffer>
    { 
        public int             ProductDiscountOfferId   { get; set; }
        public int             ProductId                { get; set; }
        public int             DiscountOfferId          { get; set; }
        public string          Sys_CreatedBy            { get; set; }
        public DateTimeOffset  Sys_CreatedAt            { get; set; }
        public string          Sys_UpdatedBy            { get; set; }
        public DateTimeOffset  Sys_UpdatedAt            { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< ProductDiscountOffer, ProductDiscountOfferDto >()
             .ForMember(d => d.ProductDiscountOfferId , opt => opt.MapFrom(s => s.ProductDiscountOfferId   ))
             .ForMember(d => d.ProductId              , opt => opt.MapFrom(s => s.ProductId                ))
             .ForMember(d => d.DiscountOfferId        , opt => opt.MapFrom(s => s.DiscountOfferId          ))
             .ForMember(d => d.Sys_CreatedBy          , opt => opt.MapFrom(s => s.Sys_CreatedBy            ))
             .ForMember(d => d.Sys_CreatedAt          , opt => opt.MapFrom(s => s.Sys_CreatedAt            ))
             .ForMember(d => d.Sys_UpdatedBy          , opt => opt.MapFrom(s => s.Sys_UpdatedBy            ))
             .ForMember(d => d.Sys_UpdatedAt          , opt => opt.MapFrom(s => s.Sys_UpdatedAt            ))
             ;
    }
    }



