/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Dto;
 
    using System;
    using AutoMapper;
    using Poseidon.Domain;
    using System.Collections.Generic;


    public class ProductDto : IMapFrom<Product>
    { 
        public int             ProductId       { get; set; }
        public string          Name            { get; set; }
        public string          Number          { get; set; }
        public string          ImageUrl        { get; set; }
        public string          Unit            { get; set; }
        public decimal         Price           { get; set; }
        public string          Description     { get; set; }
        public string          Gtin            { get; set; }
        public string          Supplier        { get; set; }
        public int?            TaxRateId       { get; set; }
        public int?            CategoryId      { get; set; }
        public string          Sys_CreatedBy   { get; set; }
        public DateTimeOffset  Sys_CreatedAt   { get; set; }
        public string          Sys_UpdatedBy   { get; set; }
        public DateTimeOffset  Sys_UpdatedAt   { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< Product, ProductDto >()
             .ForMember(d => d.ProductId     , opt => opt.MapFrom(s => s.ProductId       ))
             .ForMember(d => d.Name          , opt => opt.MapFrom(s => s.Name            ))
             .ForMember(d => d.Number        , opt => opt.MapFrom(s => s.Number          ))
             .ForMember(d => d.ImageUrl      , opt => opt.MapFrom(s => s.ImageUrl        ))
             .ForMember(d => d.Unit          , opt => opt.MapFrom(s => s.Unit            ))
             .ForMember(d => d.Price         , opt => opt.MapFrom(s => s.Price           ))
             .ForMember(d => d.Description   , opt => opt.MapFrom(s => s.Description     ))
             .ForMember(d => d.Gtin          , opt => opt.MapFrom(s => s.Gtin            ))
             .ForMember(d => d.Supplier      , opt => opt.MapFrom(s => s.Supplier        ))
             .ForMember(d => d.TaxRateId     , opt => opt.MapFrom(s => s.TaxRateId       ))
             .ForMember(d => d.CategoryId    , opt => opt.MapFrom(s => s.CategoryId      ))
             .ForMember(d => d.Sys_CreatedBy , opt => opt.MapFrom(s => s.Sys_CreatedBy   ))
             .ForMember(d => d.Sys_CreatedAt , opt => opt.MapFrom(s => s.Sys_CreatedAt   ))
             .ForMember(d => d.Sys_UpdatedBy , opt => opt.MapFrom(s => s.Sys_UpdatedBy   ))
             .ForMember(d => d.Sys_UpdatedAt , opt => opt.MapFrom(s => s.Sys_UpdatedAt   ))
             ;
    }
    }



