/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Dto;
 
    using System;
    using AutoMapper;
    using Poseidon.Domain;
    using System.Collections.Generic;


    public class SettingsDto : IMapFrom<Settings>
    { 
        public int             SettingsId            { get; set; }
        public string          Description           { get; set; }
        public decimal?        OrderDiscountAmount   { get; set; }
        public decimal?        OrderTaxAmount        { get; set; }
        public decimal?        PaymentFeeAmount      { get; set; }
        public decimal?        ShippingFeeAmount     { get; set; }
        public string          ShippingMethod        { get; set; }
        public string          PaymentMethod         { get; set; }
        public string          Supplier              { get; set; }
        public string          Sys_CreatedBy         { get; set; }
        public DateTimeOffset  Sys_CreatedAt         { get; set; }
        public string          Sys_UpdatedBy         { get; set; }
        public DateTimeOffset  Sys_UpdatedAt         { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< Settings, SettingsDto >()
             .ForMember(d => d.SettingsId          , opt => opt.MapFrom(s => s.SettingsId            ))
             .ForMember(d => d.Description         , opt => opt.MapFrom(s => s.Description           ))
             .ForMember(d => d.OrderDiscountAmount , opt => opt.MapFrom(s => s.OrderDiscountAmount   ))
             .ForMember(d => d.OrderTaxAmount      , opt => opt.MapFrom(s => s.OrderTaxAmount        ))
             .ForMember(d => d.PaymentFeeAmount    , opt => opt.MapFrom(s => s.PaymentFeeAmount      ))
             .ForMember(d => d.ShippingFeeAmount   , opt => opt.MapFrom(s => s.ShippingFeeAmount     ))
             .ForMember(d => d.ShippingMethod      , opt => opt.MapFrom(s => s.ShippingMethod        ))
             .ForMember(d => d.PaymentMethod       , opt => opt.MapFrom(s => s.PaymentMethod         ))
             .ForMember(d => d.Supplier            , opt => opt.MapFrom(s => s.Supplier              ))
             .ForMember(d => d.Sys_CreatedBy       , opt => opt.MapFrom(s => s.Sys_CreatedBy         ))
             .ForMember(d => d.Sys_CreatedAt       , opt => opt.MapFrom(s => s.Sys_CreatedAt         ))
             .ForMember(d => d.Sys_UpdatedBy       , opt => opt.MapFrom(s => s.Sys_UpdatedBy         ))
             .ForMember(d => d.Sys_UpdatedAt       , opt => opt.MapFrom(s => s.Sys_UpdatedAt         ))
             ;
    }
    }



