/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Dto;
 
    using System;
    using AutoMapper;
    using Poseidon.Domain;
    using System.Collections.Generic;


    public class UserProductReviewDto : IMapFrom<UserProductReview>
    { 
        public int             UserProductReviewId   { get; set; }
        public int             UserId                { get; set; }
        public int             ProductId             { get; set; }
        public string          Title                 { get; set; }
        public string          Comment               { get; set; }
        public short           Rating                { get; set; }
        public string          Sys_CreatedBy         { get; set; }
        public DateTimeOffset  Sys_CreatedAt         { get; set; }
        public string          Sys_UpdatedBy         { get; set; }
        public DateTimeOffset  Sys_UpdatedAt         { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< UserProductReview, UserProductReviewDto >()
             .ForMember(d => d.UserProductReviewId , opt => opt.MapFrom(s => s.UserProductReviewId   ))
             .ForMember(d => d.UserId              , opt => opt.MapFrom(s => s.UserId                ))
             .ForMember(d => d.ProductId           , opt => opt.MapFrom(s => s.ProductId             ))
             .ForMember(d => d.Title               , opt => opt.MapFrom(s => s.Title                 ))
             .ForMember(d => d.Comment             , opt => opt.MapFrom(s => s.Comment               ))
             .ForMember(d => d.Rating              , opt => opt.MapFrom(s => s.Rating                ))
             .ForMember(d => d.Sys_CreatedBy       , opt => opt.MapFrom(s => s.Sys_CreatedBy         ))
             .ForMember(d => d.Sys_CreatedAt       , opt => opt.MapFrom(s => s.Sys_CreatedAt         ))
             .ForMember(d => d.Sys_UpdatedBy       , opt => opt.MapFrom(s => s.Sys_UpdatedBy         ))
             .ForMember(d => d.Sys_UpdatedAt       , opt => opt.MapFrom(s => s.Sys_UpdatedAt         ))
             ;
    }
    }



