/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Dto;
 
    using System;
    using AutoMapper;
    using Poseidon.Domain;
    using System.Collections.Generic;


    public class UserDto : IMapFrom<User>
    { 
        public int             UserId          { get; set; }
        public string          ExternalRef     { get; set; }
        public string          Username        { get; set; }
        public string          FirstName       { get; set; }
        public string          PhoneNumber     { get; set; }
        public string          LastName        { get; set; }
        public string          Email           { get; set; }
        public string          ImageUrl        { get; set; }
        public int             AddressId       { get; set; }
        public string          Sys_CreatedBy   { get; set; }
        public DateTimeOffset  Sys_CreatedAt   { get; set; }
        public string          Sys_UpdatedBy   { get; set; }
        public DateTimeOffset  Sys_UpdatedAt   { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< User, UserDto >()
             .ForMember(d => d.UserId        , opt => opt.MapFrom(s => s.UserId          ))
             .ForMember(d => d.ExternalRef   , opt => opt.MapFrom(s => s.ExternalRef     ))
             .ForMember(d => d.Username      , opt => opt.MapFrom(s => s.Username        ))
             .ForMember(d => d.FirstName     , opt => opt.MapFrom(s => s.FirstName       ))
             .ForMember(d => d.PhoneNumber   , opt => opt.MapFrom(s => s.PhoneNumber     ))
             .ForMember(d => d.LastName      , opt => opt.MapFrom(s => s.LastName        ))
             .ForMember(d => d.Email         , opt => opt.MapFrom(s => s.Email           ))
             .ForMember(d => d.ImageUrl      , opt => opt.MapFrom(s => s.ImageUrl        ))
             .ForMember(d => d.AddressId     , opt => opt.MapFrom(s => s.AddressId       ))
             .ForMember(d => d.Sys_CreatedBy , opt => opt.MapFrom(s => s.Sys_CreatedBy   ))
             .ForMember(d => d.Sys_CreatedAt , opt => opt.MapFrom(s => s.Sys_CreatedAt   ))
             .ForMember(d => d.Sys_UpdatedBy , opt => opt.MapFrom(s => s.Sys_UpdatedBy   ))
             .ForMember(d => d.Sys_UpdatedAt , opt => opt.MapFrom(s => s.Sys_UpdatedAt   ))
             ;
    }
    }



