/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Dto;
 
    using System;
    using AutoMapper;
    using Poseidon.Domain;
    using System.Collections.Generic;


    public class WishListItemDto : IMapFrom<WishListItem>
    { 
        public int             WishListItemId   { get; set; }
        public string          Note             { get; set; }
        public decimal?        Quantity         { get; set; }
        public int             WishListId       { get; set; }
        public int             ProductId        { get; set; }
        public string          Sys_CreatedBy    { get; set; }
        public DateTimeOffset  Sys_CreatedAt    { get; set; }
        public string          Sys_UpdatedBy    { get; set; }
        public DateTimeOffset  Sys_UpdatedAt    { get; set; }



    public void Mapping(Profile profile)
    {  
          profile.CreateMap< WishListItem, WishListItemDto >()
             .ForMember(d => d.WishListItemId , opt => opt.MapFrom(s => s.WishListItemId   ))
             .ForMember(d => d.Note           , opt => opt.MapFrom(s => s.Note             ))
             .ForMember(d => d.Quantity       , opt => opt.MapFrom(s => s.Quantity         ))
             .ForMember(d => d.WishListId     , opt => opt.MapFrom(s => s.WishListId       ))
             .ForMember(d => d.ProductId      , opt => opt.MapFrom(s => s.ProductId        ))
             .ForMember(d => d.Sys_CreatedBy  , opt => opt.MapFrom(s => s.Sys_CreatedBy    ))
             .ForMember(d => d.Sys_CreatedAt  , opt => opt.MapFrom(s => s.Sys_CreatedAt    ))
             .ForMember(d => d.Sys_UpdatedBy  , opt => opt.MapFrom(s => s.Sys_UpdatedBy    ))
             .ForMember(d => d.Sys_UpdatedAt  , opt => opt.MapFrom(s => s.Sys_UpdatedAt    ))
             ;
    }
    }



