/**************************************************************
* This code is generated by custom generator  
*************************************************************/
namespace Poseidon.Application.Commands;

using MediatR;
using Poseidon.Enums;
using System;


    public partial class AddressCommand : IRequest<(object id, Status status)>
    { 
        public object?  AddressId       { get; set; }
        public object?  FirstName       { get; set; }
        public object?  LastName        { get; set; }
        public object?  Email           { get; set; }
        public object?  Company         { get; set; }
        public object?  County          { get; set; }
        public object?  City            { get; set; }
        public object?  Address1        { get; set; }
        public object?  Address2        { get; set; }
        public object?  ZipPostalCode   { get; set; }
        public object?  PhoneNumber     { get; set; }
        public object?  CountryId       { get; set; }
    } 
    public partial class CartCommand : IRequest<(object id, Status status)>
    { 
        public object?  CartId             { get; set; }
        public object?  IsActive           { get; set; }
        public object?  LockedOnCheckout   { get; set; }
        public object?  UserId             { get; set; }
        public object?  Total              { get; set; }
        public object?  TaxAmount          { get; set; }
        public object?  DiscountAmount     { get; set; }
    } 
    public partial class CartItemCommand : IRequest<(object id, Status status)>
    { 
        public object?  CartItemId       { get; set; }
        public object?  Quantity         { get; set; }
        public object?  Price            { get; set; }
        public object?  DiscountAmount   { get; set; }
        public object?  TaxAmount        { get; set; }
        public object?  Title            { get; set; }
        public object?  ImageUrl         { get; set; }
        public object?  Unit             { get; set; }
        public object?  CartId           { get; set; }
        public object?  ProductId        { get; set; }
    } 
    public partial class CategoryCommand : IRequest<(object id, Status status)>
    { 
        public object?  CategoryId      { get; set; }
        public object?  Name            { get; set; }
    } 
    public partial class CountryCommand : IRequest<(object id, Status status)>
    { 
        public object?  CountryId            { get; set; }
        public object?  Name                 { get; set; }
        public object?  TwoLetterIsoCode     { get; set; }
        public object?  ThreeLetterIsoCode   { get; set; }
        public object?  NumericIsoCode       { get; set; }
        public object?  PhonePrefix          { get; set; }
    } 
    public partial class CreditCardCommand : IRequest<(object id, Status status)>
    { 
        public object?  CreditCardId        { get; set; }
        public object?  CreaditCartNumber   { get; set; }
        public object?  CVC                 { get; set; }
        public object?  ExpirationDate      { get; set; }
        public object?  ImageUrl            { get; set; }
        public object?  UserId              { get; set; }
        public object?  PaymentProviderId   { get; set; }
    } 
    public partial class DeliveryCommand : IRequest<(object id, Status status)>
    { 
        public object?  DeliveryId      { get; set; }
        public object?  Title           { get; set; }
        public object?  Description     { get; set; }
        public object?  IsActive        { get; set; }
    } 
    public partial class DiscountOfferCommand : IRequest<(object id, Status status)>
    { 
        public object?  DiscountOfferId   { get; set; }
        public object?  Title             { get; set; }
        public object?  Description       { get; set; }
        public object?  ImageUrl          { get; set; }
        public object?  StartDate         { get; set; }
        public object?  EndDate           { get; set; }
        public object?  Discount          { get; set; }
    } 
    public partial class OrderCommand : IRequest<(object id, Status status)>
    { 
        public object?  OrderId                 { get; set; }
        public object?  Description             { get; set; }
        public object?  SubTotal                { get; set; }
        public object?  ProductTaxAmount        { get; set; }
        public object?  ProductDiscountAmount   { get; set; }
        public object?  OrderDiscountAmount     { get; set; }
        public object?  OrderTaxAmount          { get; set; }
        public object?  OrderTotal              { get; set; }
        public object?  OrderStatus             { get; set; }
        public object?  PayedAndClosed          { get; set; }
        public object?  ShippingMethod          { get; set; }
        public object?  ShippingFeeAmount       { get; set; }
        public object?  PaymentMethod           { get; set; }
        public object?  PaymentFeeAmount        { get; set; }
        public object?  ShippingAddressId       { get; set; }
        public object?  BillingAddressId        { get; set; }
        public object?  UserId                  { get; set; }
        public object?  CartId                  { get; set; }
        public object?  DeliveryId              { get; set; }
    } 
    public partial class OrderItemCommand : IRequest<(object id, Status status)>
    { 
        public object?  OrderItemId      { get; set; }
        public object?  ProductID        { get; set; }
        public object?  OrderID          { get; set; }
        public object?  ProductPrice     { get; set; }
        public object?  Quantity         { get; set; }
        public object?  DiscountAmount   { get; set; }
        public object?  TaxAmount        { get; set; }
    } 
    public partial class PaymentCommand : IRequest<(object id, Status status)>
    { 
        public object?  PaymentId           { get; set; }
        public object?  Amount              { get; set; }
        public object?  PaymentFee          { get; set; }
        public object?  FailureMessage      { get; set; }
        public object?  OrderId             { get; set; }
        public object?  PaymentProviderId   { get; set; }
    } 
    public partial class PaymentProviderCommand : IRequest<(object id, Status status)>
    { 
        public object?  PaymentProviderId    { get; set; }
        public object?  Name                 { get; set; }
        public object?  IsEnabled            { get; set; }
        public object?  AdditionalSettings   { get; set; }
    } 
    public partial class ProductCommand : IRequest<(object id, Status status)>
    { 
        public object?  ProductId       { get; set; }
        public object?  Name            { get; set; }
        public object?  Number          { get; set; }
        public object?  ImageUrl        { get; set; }
        public object?  Unit            { get; set; }
        public object?  Price           { get; set; }
        public object?  Description     { get; set; }
        public object?  Gtin            { get; set; }
        public object?  Supplier        { get; set; }
        public object?  TaxRateId       { get; set; }
        public object?  CategoryId      { get; set; }
    } 
    public partial class ProductDiscountOfferCommand : IRequest<(object id, Status status)>
    { 
        public object?  ProductDiscountOfferId   { get; set; }
        public object?  ProductID                { get; set; }
        public object?  DiscountOfferID          { get; set; }
    } 
    public partial class SettingsCommand : IRequest<(object id, Status status)>
    { 
        public object?  SettingsId            { get; set; }
        public object?  Description           { get; set; }
        public object?  OrderDiscountAmount   { get; set; }
        public object?  OrderTaxAmount        { get; set; }
        public object?  PaymentFeeAmount      { get; set; }
        public object?  ShippingFeeAmount     { get; set; }
        public object?  ShippingMethod        { get; set; }
        public object?  PaymentMethod         { get; set; }
        public object?  Supplier              { get; set; }
    } 
    public partial class TaxRateCommand : IRequest<(object id, Status status)>
    { 
        public object?  TaxRateId       { get; set; }
        public object?  Name            { get; set; }
        public object?  Rate            { get; set; }
    } 
    public partial class UserCommand : IRequest<(object id, Status status)>
    { 
        public object?  UserId          { get; set; }
        public object?  ExternalRef     { get; set; }
        public object?  Username        { get; set; }
        public object?  FirstName       { get; set; }
        public object?  PhoneNumber     { get; set; }
        public object?  LastName        { get; set; }
        public object?  Email           { get; set; }
        public object?  ImageUrl        { get; set; }
        public object?  AddressId       { get; set; }
    } 
    public partial class UserProductReviewCommand : IRequest<(object id, Status status)>
    { 
        public object?  UserProductReviewId   { get; set; }
        public object?  UserID                { get; set; }
        public object?  ProductID             { get; set; }
        public object?  Title                 { get; set; }
        public object?  Comment               { get; set; }
        public object?  Rating                { get; set; }
    } 
    public partial class WishListCommand : IRequest<(object id, Status status)>
    { 
        public object?  WishListId      { get; set; }
        public object?  Title           { get; set; }
        public object?  Description     { get; set; }
        public object?  UserId          { get; set; }
    } 
    public partial class WishListItemCommand : IRequest<(object id, Status status)>
    { 
        public object?  WishListItemId   { get; set; }
        public object?  Note             { get; set; }
        public object?  Quantity         { get; set; }
        public object?  WishListId       { get; set; }
        public object?  ProductId        { get; set; }
    } 



