/**************************************************************
* This code is generated by custom generator  
**************************************************************/
    class Address extends AddressDto with ChangeNotifier
    { 
          Address( AddressDto dto): super(
              addressId : dto.addressId,
              address1 : dto.address1,
              address2 : dto.address2,
              city : dto.city,
              company : dto.company,
              countryId : dto.countryId,
              county : dto.county,
              email : dto.email,
              firstName : dto.firstName,
              lastName : dto.lastName,
              phoneNumber : dto.phoneNumber,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              zipPostalCode : dto.zipPostalCode,
              );
    }
    class Cart extends CartDto with ChangeNotifier
    { 
          Cart( CartDto dto): super(
              cartId : dto.cartId,
              isActive : dto.isActive,
              lockedOnCheckout : dto.lockedOnCheckout,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              userId : dto.userId,
              );
    }
    class CartItem extends CartItemDto with ChangeNotifier
    { 
          CartItem( CartItemDto dto): super(
              cartItemId : dto.cartItemId,
              cartId : dto.cartId,
              imageUrl : dto.imageUrl,
              price : dto.price,
              productId : dto.productId,
              quantity : dto.quantity,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              title : dto.title,
              unit : dto.unit,
              );
    }
    class Category extends CategoryDto with ChangeNotifier
    { 
          Category( CategoryDto dto): super(
              categoryId : dto.categoryId,
              name : dto.name,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              );
    }
    class Country extends CountryDto with ChangeNotifier
    { 
          Country( CountryDto dto): super(
              countryId : dto.countryId,
              name : dto.name,
              numericIsoCode : dto.numericIsoCode,
              phonePrefix : dto.phonePrefix,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              threeLetterIsoCode : dto.threeLetterIsoCode,
              twoLetterIsoCode : dto.twoLetterIsoCode,
              );
    }
    class CreditCard extends CreditCardDto with ChangeNotifier
    { 
          CreditCard( CreditCardDto dto): super(
              creditCardId : dto.creditCardId,
              cVC : dto.cVC,
              creaditCartNumber : dto.creaditCartNumber,
              expirationDate : dto.expirationDate,
              imageUrl : dto.imageUrl,
              paymentProviderId : dto.paymentProviderId,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              userId : dto.userId,
              );
    }
    class Delivery extends DeliveryDto with ChangeNotifier
    { 
          Delivery( DeliveryDto dto): super(
              deliveryId : dto.deliveryId,
              description : dto.description,
              isActive : dto.isActive,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              title : dto.title,
              );
    }
    class DiscountOffer extends DiscountOfferDto with ChangeNotifier
    { 
          DiscountOffer( DiscountOfferDto dto): super(
              discountOfferId : dto.discountOfferId,
              description : dto.description,
              discount : dto.discount,
              endDate : dto.endDate,
              imageUrl : dto.imageUrl,
              startDate : dto.startDate,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              title : dto.title,
              );
    }
    class Order extends OrderDto with ChangeNotifier
    { 
          Order( OrderDto dto): super(
              orderId : dto.orderId,
              billingAddressId : dto.billingAddressId,
              cartId : dto.cartId,
              deliveryId : dto.deliveryId,
              description : dto.description,
              discountAmount : dto.discountAmount,
              orderStatus : dto.orderStatus,
              orderTotal : dto.orderTotal,
              payedAndClosed : dto.payedAndClosed,
              paymentFeeAmount : dto.paymentFeeAmount,
              paymentMethod : dto.paymentMethod,
              shippingAddressId : dto.shippingAddressId,
              shippingFeeAmount : dto.shippingFeeAmount,
              shippingMethod : dto.shippingMethod,
              subTotal : dto.subTotal,
              subTotalWithDiscount : dto.subTotalWithDiscount,
              subTotalWithFees : dto.subTotalWithFees,
              subTotalWithOrderTax : dto.subTotalWithOrderTax,
              subTotalWithProductTax : dto.subTotalWithProductTax,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              taxAmount : dto.taxAmount,
              userId : dto.userId,
              );
    }
    class OrderItem extends OrderItemDto with ChangeNotifier
    { 
          OrderItem( OrderItemDto dto): super(
              orderItemId : dto.orderItemId,
              discountAmount : dto.discountAmount,
              orderId : dto.orderId,
              productId : dto.productId,
              productPrice : dto.productPrice,
              quantity : dto.quantity,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              taxAmount : dto.taxAmount,
              );
    }
    class Payment extends PaymentDto with ChangeNotifier
    { 
          Payment( PaymentDto dto): super(
              paymentId : dto.paymentId,
              amount : dto.amount,
              failureMessage : dto.failureMessage,
              orderId : dto.orderId,
              paymentFee : dto.paymentFee,
              paymentProviderId : dto.paymentProviderId,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              );
    }
    class PaymentProvider extends PaymentProviderDto with ChangeNotifier
    { 
          PaymentProvider( PaymentProviderDto dto): super(
              paymentProviderId : dto.paymentProviderId,
              additionalSettings : dto.additionalSettings,
              isEnabled : dto.isEnabled,
              name : dto.name,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              );
    }
    class Product extends ProductDto with ChangeNotifier
    { 
          Product( ProductDto dto): super(
              productId : dto.productId,
              categoryId : dto.categoryId,
              description : dto.description,
              gtin : dto.gtin,
              imageUrl : dto.imageUrl,
              name : dto.name,
              number : dto.number,
              price : dto.price,
              supplier : dto.supplier,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              taxRateId : dto.taxRateId,
              unit : dto.unit,
              );
    }
    class ProductDiscountOffer extends ProductDiscountOfferDto with ChangeNotifier
    { 
          ProductDiscountOffer( ProductDiscountOfferDto dto): super(
              productDiscountOfferId : dto.productDiscountOfferId,
              discountOfferId : dto.discountOfferId,
              productId : dto.productId,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              );
    }
    class Settings extends SettingsDto with ChangeNotifier
    { 
          Settings( SettingsDto dto): super(
              settingsId : dto.settingsId,
              description : dto.description,
              orderDiscountAmount : dto.orderDiscountAmount,
              orderTaxAmount : dto.orderTaxAmount,
              paymentFeeAmount : dto.paymentFeeAmount,
              paymentMethod : dto.paymentMethod,
              shippingFeeAmount : dto.shippingFeeAmount,
              shippingMethod : dto.shippingMethod,
              supplier : dto.supplier,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              );
    }
    class TaxRate extends TaxRateDto with ChangeNotifier
    { 
          TaxRate( TaxRateDto dto): super(
              taxRateId : dto.taxRateId,
              name : dto.name,
              rate : dto.rate,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              );
    }
    class User extends UserDto with ChangeNotifier
    { 
          User( UserDto dto): super(
              userId : dto.userId,
              addressId : dto.addressId,
              email : dto.email,
              externalRef : dto.externalRef,
              firstName : dto.firstName,
              imageUrl : dto.imageUrl,
              lastName : dto.lastName,
              phoneNumber : dto.phoneNumber,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              username : dto.username,
              );
    }
    class UserProductReview extends UserProductReviewDto with ChangeNotifier
    { 
          UserProductReview( UserProductReviewDto dto): super(
              userProductReviewId : dto.userProductReviewId,
              comment : dto.comment,
              productId : dto.productId,
              rating : dto.rating,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              title : dto.title,
              userId : dto.userId,
              );
    }
    class WishList extends WishListDto with ChangeNotifier
    { 
          WishList( WishListDto dto): super(
              wishListId : dto.wishListId,
              description : dto.description,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              title : dto.title,
              userId : dto.userId,
              );
    }
    class WishListItem extends WishListItemDto with ChangeNotifier
    { 
          WishListItem( WishListItemDto dto): super(
              wishListItemId : dto.wishListItemId,
              note : dto.note,
              productId : dto.productId,
              quantity : dto.quantity,
              sysCreatedAt : dto.sysCreatedAt,
              sysCreatedBy : dto.sysCreatedBy,
              sysDeactivated : dto.sysDeactivated,
              sysDisplayOrder : dto.sysDisplayOrder,
              sysUpdatedAt : dto.sysUpdatedAt,
              sysUpdatedBy : dto.sysUpdatedBy,
              wishListId : dto.wishListId,
              );
    }
